language: objective-c
osx_image: xcode7.0
env:
  global:
    - LANG=en_US.UTF-8
    - LC_ALL=en_US.UTF-8
script:
- xcodebuild test -project Sample/Sample.xcodeproj -configuration Debug -derivedDataPath build -destination 'name=iPhone 5s' -scheme Sample
