language: objective-c
osx_image: xcode6.4
env:
  global:
  - LANG=en_US.UTF-8
  - LC_ALL=en_US.UTF-8
script:
- xcodebuild test -project Sample/Sample.xcodeproj -scheme Sample -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
